port="8888"
dev = true

[database]
db_host="localhost"
# db_host="192.168.199.23"
db_port="3306"
db_schema_name="payment_bridge"
db_username="root"
# db_username="filswan"
db_pwd="password"
# db_pwd="vancouver2021199!A"
db_args="charset=utf8mb4&parseTime=True&loc=Local"
